openapi: 3.0.0
info:
  title: Ask Big Ben ChatGPT Plugin
  version: 1.0.0
servers:
  - url: http://localhost:3000/api
paths:
  /hello:
    get:
      summary: Say hello
      description: Says hello from the plugin
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
      operationId: sayAskBigBen
