openapi: 3.0.0
info:
  title: Ask Big Ben ChatGPT Plugin
  version: 1.0.0
servers:
  - url: http://localhost:3000/api
paths:
  /ask_big_ben:
    get:
      summary: Say I'd like to ask big ben something about a member of parliament
      description: Says What would you like to ask big ben?
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
      operationId: sayAskBigBen
